**Reference**: Dive into Deep Learning -- ASTON ZHANG

https://drive.google.com/file/d/1bV_z9nx2dF2oSqM5ly82izKmWwgi9ylj/view?usp=drive_link

# torch.arange()


In [1]:
import torch

x = torch.arange(12, dtype=torch.float32)
print(x)
print(x.numel())
print(x.shape)

X = x.reshape(3, 4)
print(X)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12
torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


# torch.zeros()


In [2]:
import torch

x = torch.zeros((2, 3, 4))
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


# torch.ones()


In [3]:
import torch

x = torch.ones((2, 3, 4))
print(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


# torch.randn()


In [4]:
import torch

x = torch.randn(3, 4)
print(x)

tensor([[ 0.7120,  0.1827,  0.1958, -0.7868],
        [-0.6093, -1.6479,  0.8631,  1.1127],
        [ 0.2990,  0.5038,  0.2990,  1.0472]])


# torch.tensor()


In [5]:
import torch

x = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(x)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


## Indexing and Slicing


In [6]:
import torch

x = torch.arange(12, dtype=torch.float32)
X = x.reshape(3, 4)
print(X)

print(X[-1])

print(X[1:3])

X[1, 2] = 17
print(X)

X[:2, :] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## Operators


In [7]:
import torch

x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print(x + y, x - y, x * y, x / y, x**y, sep="\n")

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


## Concatenate


In [8]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1), sep="\n")

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## Logical statements


In [9]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print(X == Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


## Sum of elements


In [10]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(X.sum())

tensor(66.)


## Broadcasting


In [11]:
import torch

a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a, b, sep="\n")
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


# torch.exp()


In [12]:
import torch

x = torch.randn((3, 4))
print(x)
print(torch.exp(x))

tensor([[-1.4513,  0.5437,  0.4488,  0.2563],
        [-0.8499,  0.7424,  1.2159,  2.0446],
        [ 0.0771, -1.1566,  0.6754,  1.4588]])
tensor([[0.2343, 1.7224, 1.5665, 1.2922],
        [0.4275, 2.1009, 3.3732, 7.7257],
        [1.0801, 0.3145, 1.9648, 4.3010]])


# Saving Memory


## Normal


In [13]:
X, Y = 5, 10
print(id(X), id(Y))

before = id(Y)
Y = Y + X
print(id(Y) == before)

140704037331880 140704037332040
False


## torch (in-place updates)


In [14]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = torch.zeros_like(Y)
print(X, Y, Z, sep="\n")
print(id(Z))

Z[:] = X + Y
print(id(Z))

Z = X + Y
print(id(Z))

print(id(X))
before = id(X)
X += Y
print(id(X))
print(id(X) == before)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
1623250026032
1623250026032
1623250012784
1623250015856
1623250015856
True


# Conversion


## To Numpy


In [15]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(X)

A = X.numpy()
print(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## From Numpy


In [16]:
import numpy as np
import torch

A = np.arange(12, dtype=np.float32).reshape((3, 4))
print(A)

X = torch.from_numpy(A)
print(X)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


## To and From Python built-in objects


In [17]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(X)
A = X.tolist()
print(A)
print(list(X))
X = torch.tensor(A)
print(X)

a = torch.tensor([3.5])
print(a, a.item(), float(a), int(a), sep="\n")

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
[[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0]]
[tensor([0., 1., 2., 3.]), tensor([4., 5., 6., 7.]), tensor([ 8.,  9., 10., 11.])]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([3.5000])
3.5
3.5
3
