**Reference**: Dive into Deep Learning -- ASTON ZHANG

https://drive.google.com/file/d/1bV_z9nx2dF2oSqM5ly82izKmWwgi9ylj/view?usp=drive_link

In [1]:
import torch

## Scalars

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

print(x + y, x * y, x / y, x**y, sep="\n")

tensor(5.)
tensor(6.)
tensor(1.5000)
tensor(9.)


## Vectors

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
print(x[2], len(x), x.shape, sep="\n")

tensor(2)
3
torch.Size([3])


## Matrices

In [5]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [7]:
# symmetric matrix test

A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(A == A.T)
print(all((A == A.T).tolist()))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
True


## Tensors

In [8]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
print(A, A + B, sep="\n")

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


In [10]:
# Hadamard product (A ⊙ B)

A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [11]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(a + X, (a * X).shape, sep="\n")

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


In [12]:
x = torch.arange(3, dtype=torch.float32)
print(x, x.sum(), sep="\n")

tensor([0., 1., 2.])
tensor(3.)


In [13]:
print(A.shape, A.sum(), sep="\n")

torch.Size([2, 3])
tensor(15.)


In [14]:
print(A.shape, A.sum(axis=0).shape, sep="\n")

torch.Size([2, 3])
torch.Size([3])


In [15]:
print(A.shape, A.sum(axis=1).shape, sep="\n")

torch.Size([2, 3])
torch.Size([2])


In [16]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [17]:
print(A.mean(), A.sum() / A.numel(), sep="\n")

tensor(2.5000)
tensor(2.5000)


In [18]:
print(A.mean(axis=0), A.sum(axis=0) / A.shape[0], sep="\n")

tensor([1.5000, 2.5000, 3.5000])
tensor([1.5000, 2.5000, 3.5000])


In [19]:
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A, sum_A.shape, sep="\n")

tensor([[ 3.],
        [12.]])
torch.Size([2, 1])


In [20]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [21]:
"""
cumulative sum of elements of A along some axis, say axis=0 (row by row), we
can call the cumsum function. By design, this function does not reduce the
input tensor along any axis.
"""

A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## Dot Product

In [22]:
y = torch.ones(3, dtype=torch.float32)
print(x, y, torch.dot(x, y), sep="\n")

tensor([0., 1., 2.])
tensor([1., 1., 1.])
tensor(3.)


In [23]:
torch.sum(x * y)

tensor(3.)

## Matrix-Vector Products

In [24]:
print(A.shape, x.shape, torch.mv(A, x), A @ x, sep="\n")

torch.Size([2, 3])
torch.Size([3])
tensor([ 5., 14.])
tensor([ 5., 14.])


## Matrix-Matrix Multiplication

In [25]:
B = torch.ones(3, 4)
print(torch.mm(A, B), A @ B, sep="\n")

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])
tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])


## Norms

In [26]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)  # l2 norm

tensor(5.)

In [27]:
torch.abs(u).sum()  # l1 norm

tensor(7.)

In [28]:
torch.norm(torch.ones((4, 9)))  # Frobenius norm

tensor(6.)