In [1]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

2024-06-13 14:57:55.633836: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-13 14:57:56.810675: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Instructions for updating:
non-resource variables are not supported in the long term


# Session & Graph

In [2]:
sess = tf.Session()
sess

2024-06-13 14:57:59.762957: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-13 14:57:59.763624: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [3]:
graph = tf.Graph()
graph

In [4]:
with graph.as_default():
    variable = tf.Variable(30, name="navin")
    initialize = tf.global_variables_initializer()

In [5]:
with tf.Session(graph=graph) as sess:
    sess.run(initialize)
    print(sess.run(variable))

30


2024-06-13 14:57:59.805795: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled


In [9]:
graph.operations

[<tf.Operation 'navin/initial_value' type=Const>,
 <tf.Operation 'navin' type=VariableV2>,
 <tf.Operation 'navin/Assign' type=Assign>,
 <tf.Operation 'navin/read' type=Identity>,
 <tf.Operation 'init' type=NoOp>]

In [6]:
import os

merged = tf.summary.merge_all(key="summaries")

if not os.path.exists("../tensorboard_logs/0001/"):
    os.makedirs("../tensorboard_logs/0001/", exist_ok=True)

my_writer = tf.summary.FileWriter("../tensorboard_logs/0001/", sess.graph)


def TB(cleanup=False):
    import webbrowser

    webbrowser.open("http://127.0.0.1:6006")

    !tensorboard --logdir="../tensorboard_logs/0001/"

    if cleanup:
        !rm -r "../tensorboard_logs/0001/"


# TB()

# Constants, Placeholders, and Variables

In [7]:
x = tf.constant(12, dtype="float32")
sess = tf.Session()
print(sess.run(x))

12.0


In [10]:
x = tf.constant(12, dtype="float32")
with tf.Session() as sess:
    print(sess.run(x))

12.0


In [12]:
# Create a constant value called x and give it the numerical value 12.
x = tf.constant(12, dtype="float32")

# Create a variable called y and define it as being the equation 12+11.
y = tf.Variable(x + 11)

# Initialize the variables with tf.global_variables_initializer().
model = tf.global_variables_initializer()

# Create a session for computing the values.
with tf.Session() as sess:

    # Run the model created
    sess.run(model)

    # Run just the variable y and print out its current value.
    print(sess.run(y))

23.0


In [13]:
x = tf.constant([14, 23, 40, 30])
y = tf.Variable(x * 2 + 100)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

[128 146 180 160]


In [15]:
# Create a placeholder called x, mentioning the float type.
# The first dimension of the placeholder is None, which means any number of rows is allowed.
x = tf.placeholder("float", None)

# Create a tensor called y that is the operation of multiplying x by 10 and adding 500 to it.
# Note that any initial values for x are not defined.
y = x * 10 + 500

# Create a session for computing the values.
with tf.Session() as sess:
    # Define the values of x in feed_dict so as to run y.
    placeX = sess.run(y, feed_dict={x: [0, 5, 10, 15]})

    # Print out its value.
    print(placeX)

[500. 550. 600. 650.]


In [16]:
# 2-d

x = tf.placeholder("float", [None, 4])
y = x * 10 + 1
with tf.Session() as sess:
    dataX = [
        [12, 2, 0, -2],
        [14, 4, 1, 0],
    ]
    placeX = sess.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [17]:
# 2-d

x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as sess:
    dataX = [
        [12, 2, 0, -2],
        [14, 4, 1, 0],
    ]
    placeX = sess.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [18]:
# 2-d

x = tf.placeholder("float", [3, 4])
y = x * 10 + 1
with tf.Session() as sess:
    dataX = [
        [12, 2, 0, -2],
        [14, 4, 1, 0],
    ]
    placeX = sess.run(y, feed_dict={x: dataX})
    print(placeX)

ValueError: Cannot feed value of shape (2, 4) for Tensor Placeholder_4:0, which has shape (3, 4)